import React, { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Alert, Box, Button, Chip, CircularProgress, Paper, Typography } from '@mui/material';
import { CheckCircle2, Clock3, Inbox, RefreshCw, UserCheck, XCircle } from 'lucide-react';
import { DataPageShell, EmptyState, KpiCard, KpiGrid, ListRow, Panel, SplitGrid } from '../components/ui';
import { apiClient } from '../api/client';
export const TrainerAcceptanceChain: React.FC = () => {
 const qc=useQueryClient(); const [errorMsg,setErrorMsg]=useState<string|null>(null); const [successMsg,setSuccessMsg]=useState<string|null>(null); const [busyId,setBusyId]=useState<string|null>(null);
 const {data:requests,isLoading,refetch}=useQuery({queryKey:['trainer-acceptance-requests'],queryFn:async()=>(await apiClient.get('/operations/trainer/assignment-requests')).data?.data??[],refetchInterval:10000});
 const {data:trainees}=useQuery({queryKey:['trainer-acceptance-trainees'],queryFn:async()=>(await apiClient.get('/operations/trainer/assigned-interns')).data?.data??[],refetchInterval:15000});
 const {data:incoming}=useQuery({queryKey:['trainer-incoming-worklist'],queryFn:async()=>(await apiClient.get('/operations/trainer/incoming-requests')).data?.data??{evaluations:[],clinicalLogs:[]},refetchInterval:10000});
 const invalidate=()=>{['trainer-acceptance-requests','trainer-acceptance-trainees','trainer-incoming-worklist','tr-dashboard','notifications-unread-count','notifications-list'].forEach(k=>qc.invalidateQueries({queryKey:[k]}));};
 const accept=useMutation({mutationFn:async(id:string)=>{setBusyId(id);return(await apiClient.post(`/operations/trainer/assignment-requests/${id}/accept`)).data},onSuccess:(res:any)=>{setSuccessMsg(res?.message||'تم قبول الإسناد؛ أُرسلت الإشعارات للأطراف المعنية');setErrorMsg(null);invalidate()},onError:(e:any)=>setErrorMsg(e?.response?.data?.message||'تعذر قبول الإسناد'),onSettled:()=>setBusyId(null)});
 const reject=useMutation({mutationFn:async({id,reason}:{id:string;reason:string})=>{setBusyId(id);return(await apiClient.post(`/operations/trainer/assignment-requests/${id}/reject`,{reason})).data},onSuccess:(res:any)=>{setSuccessMsg(res?.message||'تم رفض الإسناد وإعادته للمستشفى');setErrorMsg(null);invalidate()},onError:(e:any)=>setErrorMsg(e?.response?.data?.message||'تعذر رفض الإسناد'),onSettled:()=>setBusyId(null)});
 const pendingEvaluations=incoming?.evaluations?.pendingTrainerEvals??incoming?.evaluations??[]; const clinicalLogs=incoming?.clinicalLogs??[];
 return <DataPageShell title="سلسلة القبول وإسنادات المدرب" subtitle="مراجعة الإسنادات الواردة للمدرب ومتابعة ما أصبح مسنداً إليه فعلياً" actions={<Button variant="outlined" startIcon={<RefreshCw size={16}/>} onClick={()=>{refetch();invalidate()}}>تحديث</Button>}>
 {successMsg&&<Alert severity="success" sx={{mb:2}} onClose={()=>setSuccessMsg(null)}>{successMsg}</Alert>}{errorMsg&&<Alert severity="error" sx={{mb:2}} onClose={()=>setErrorMsg(null)}>{errorMsg}</Alert>}
 <KpiGrid min={200}><KpiCard label="طلبات إسناد بانتظار قرارك" value={requests?.length??0} icon={Inbox} tone="warning"/><KpiCard label="أطباء امتياز مسندون إليك" value={trainees?.length??0} icon={UserCheck} tone="success"/><KpiCard label="تقييمات مطلوبة" value={pendingEvaluations.length} icon={Clock3} tone="violet"/><KpiCard label="سجلات بانتظار اعتمادك" value={clinicalLogs.length} icon={CheckCircle2} tone="primary"/></KpiGrid>
 <SplitGrid><Panel title="طلبات الإسناد الجديدة" icon={Inbox}>{isLoading?<Box sx={{p:4,textAlign:'center'}}><CircularProgress size={26}/></Box>:(requests?.length??0)===0?<EmptyState icon={CheckCircle2} title="لا توجد طلبات إسناد جديدة" hint="عند إسناد متدرب إليك سيظهر هنا مباشرة."/>:requests.map((r:any)=><ListRow key={r.id} title={r.traineeProfile?.person?.nameAr??'متدرب'} meta={`${r.department?.nameAr??'القسم غير محدد'} · ${r.startDate?String(r.startDate).slice(0,10):'—'} → ${r.endDate?String(r.endDate).slice(0,10):'—'}`} trailing={<Box sx={{display:'flex',gap:1,flexWrap:'wrap'}}><Button size="small" variant="contained" color="success" disabled={busyId===r.id||accept.isPending} startIcon={busyId===r.id?<CircularProgress size={13} color="inherit"/>:<CheckCircle2 size={14}/>} onClick={()=>accept.mutate(r.id)}>قبول الإسناد</Button><Button size="small" variant="outlined" color="error" disabled={busyId===r.id||reject.isPending} startIcon={<XCircle size={14}/>} onClick={()=>{const reason=window.prompt('سبب رفض الإسناد:');if(reason?.trim())reject.mutate({id:r.id,reason:reason.trim()})}}>رفض الإسناد</Button></Box>}/>)}</Panel><Panel title="المتدربون المسندون إليك" icon={UserCheck}>{(trainees?.length??0)===0?<EmptyState icon={UserCheck} title="لا يوجد متدربون مسندون حالياً" hint="سيظهر المتدرب بعد قبول الإسناد."/>:trainees.slice(0,20).map((t:any)=><ListRow key={t.id} title={t.person?.nameAr??'متدرب'} meta={`الرقم: ${t.traineeNumber??'—'} · الروتيشن: ${t.rotations?.find((r:any)=>r.status==='active')?.department?.nameAr??'—'}`} trailing={<Chip size="small" color="success" label="نشط"/>}/>)}</Panel></SplitGrid>
 <Panel title="طلبات العمل التي تحتاج إجراءً" icon={Clock3} tone="warning">{pendingEvaluations.length===0&&clinicalLogs.length===0?<EmptyState icon={CheckCircle2} title="لا توجد إجراءات معلقة" hint="سيتم تحديث القائمة تلقائياً عند وصول تقييم أو سجل سريري جديد."/>:<Box sx={{display:'grid',gap:1.5}}>{pendingEvaluations.map((e:any)=><Paper key={`e-${e.rotationId}`} sx={{p:1.5,border:'1px solid #E2E8F0'}}><Typography sx={{fontWeight:800}}>تقييم مطلوب — {e.traineeNameAr??'متدرب'}</Typography><Typography variant="body2" sx={{color:'#64748B'}}>{e.departmentNameAr??'القسم غير محدد'}</Typography><Button size="small" sx={{mt:1}} variant="contained" onClick={()=>window.location.assign('/logbook?tab=evaluations')}>فتح التقييم</Button></Paper>)}{clinicalLogs.map((l:any)=><Paper key={`l-${l.id}`} sx={{p:1.5,border:'1px solid #E2E8F0'}}><Typography sx={{fontWeight:800}}>سجل سريري بانتظار الاعتماد — {l.traineeProfile?.person?.nameAr??'متدرب'}</Typography><Typography variant="body2" sx={{color:'#64748B'}}>{l.diagnosis??'حالة سريرية'}</Typography><Button size="small" sx={{mt:1}} variant="outlined" onClick={()=>window.location.assign('/logbook')}>فتح السجل السريري</Button></Paper>)}</Box>}</Panel>
 </DataPageShell>;
};
export default TrainerAcceptanceChain;
