-- Final training workflow consistency repair.
UPDATE training_requests tr SET status='approved',updated_at=NOW()
WHERE tr.status IN ('allocated','auto_allocated','manually_reallocated') AND EXISTS (SELECT 1 FROM audit_logs al WHERE al.entity_type='TrainingRequest' AND al.entity_id=tr.id AND al.action='approve_training_request' AND COALESCE(al.new_values->>'status','')='approved');
CREATE OR REPLACE FUNCTION miran_enforce_training_request_approval_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.entity_type='TrainingRequest' AND NEW.entity_id IS NOT NULL AND NEW.action='approve_training_request' AND COALESCE(NEW.new_values->>'status','')='approved' THEN UPDATE training_requests SET status='approved',updated_at=NOW() WHERE id=NEW.entity_id AND status IN ('allocated','auto_allocated','manually_reallocated'); END IF; RETURN NEW; END; $$;
DROP TRIGGER IF EXISTS trg_training_request_approval_audit_status ON audit_logs;
CREATE TRIGGER trg_training_request_approval_audit_status AFTER INSERT ON audit_logs FOR EACH ROW EXECUTE FUNCTION miran_enforce_training_request_approval_audit();
UPDATE training_request_trainees trt SET status='documents_requested',updated_at=NOW() WHERE trt.status IN ('allocated','hospital_review','on_hold') AND jsonb_typeof(trt.required_documents)='array' AND jsonb_array_length(trt.required_documents)>0;
UPDATE training_request_trainees trt SET status='hospital_review',correction_deadline=NULL,required_documents='[]'::jsonb,updated_at=NOW() WHERE trt.status='documents_requested' AND jsonb_typeof(trt.required_documents)='array' AND jsonb_array_length(trt.required_documents)>0 AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements_text(trt.required_documents) AS required(type) WHERE NOT EXISTS (SELECT 1 FROM documents d WHERE d.training_request_trainee_id=trt.id AND d.deleted_at IS NULL AND d.document_type=required.type));
CREATE OR REPLACE FUNCTION miran_resume_after_documents_uploaded() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE row_id uuid; missing_required boolean; BEGIN row_id:=COALESCE(NEW.training_request_trainee_id,OLD.training_request_trainee_id); IF row_id IS NULL THEN RETURN NEW; END IF; SELECT EXISTS (SELECT 1 FROM jsonb_array_elements_text(COALESCE((SELECT required_documents FROM training_request_trainees WHERE id=row_id),'[]'::jsonb)) AS required(type) WHERE NOT EXISTS (SELECT 1 FROM documents d WHERE d.training_request_trainee_id=row_id AND d.deleted_at IS NULL AND d.document_type=required.type)) INTO missing_required; IF NOT missing_required THEN UPDATE training_request_trainees SET status='hospital_review',required_documents='[]'::jsonb,correction_deadline=NULL,updated_at=NOW() WHERE id=row_id AND status='documents_requested'; END IF; RETURN NEW; END; $$;
DROP TRIGGER IF EXISTS trg_documents_resume_hospital_review ON documents;
CREATE TRIGGER trg_documents_resume_hospital_review AFTER INSERT OR UPDATE OF deleted_at,document_type,training_request_trainee_id ON documents FOR EACH ROW EXECUTE FUNCTION miran_resume_after_documents_uploaded();
